language: objective-c
osx_image: xcode7.1

# xcode_project: ./DistanceHistogramMasterDetail/HybridHealthStore.xcodeproj
xcode_workspace: ./DistanceHistogramMasterDetail/HybridHealthStore.xcworkspace
xcode_scheme: HybridHealthStore
xcode_sdk: iphonesimulator9.2
podfile: ./DistanceHistogramMasterDetail/podfile

before_install:
  - brew update
  - brew upgrade xctool

script:
  - xctool test -workspace ./DistanceHistogramMasterDetail/HybridHealthStore.xcworkspace -scheme HybridHealthStore -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
